Repository ProfffUndo/Market, pull requests merged in 2021-12, with the labels that each got.

#57 Переделано то говно, что уже было, но еще раз, так как git решил удалить пару файлов)
  src/main/java/com/submarine29/market/controller/BasketController.java
  src/main/java/com/submarine29/market/controller/MainController.java
  src/main/java/com/submarine29/market/domain/Order.java
  src/main/java/com/submarine29/market/domain/OrderItem.java
  src/main/java/com/submarine29/market/domain/Product.java
  src/main/java/com/submarine29/market/domain/Status.java
  src/main/java/com/submarine29/market/services/BasketService.java
  src/main/resources/sql/data.sql
  src/main/resources/templates/basket/basket.ftlh
  src/main/resources/templates/products/list.ftlh
Labels: enhancement

#59 Market-58 Удаление из корзины
  src/main/java/com/submarine29/market/controller/BasketController.java
  src/main/java/com/submarine29/market/controller/PayPalController.java
  src/main/java/com/submarine29/market/controller/ProductController.java
  src/main/java/com/submarine29/market/services/BasketService.java
  src/main/resources/templates/basket/basket.ftlh
  src/main/resources/templates/products/show.ftlh
Labels: enhancement

#62 Market-60 Исправить логику работы корзины
  src/main/java/com/submarine29/market/controller/PayPalController.java
  src/main/java/com/submarine29/market/services/BasketService.java
Labels: bug

#66 Market-55 Сервисы валидации
  src/main/java/com/submarine29/market/controller/ControllerUtil.java
  src/main/java/com/submarine29/market/controller/ProductController.java
  src/main/java/com/submarine29/market/domain/Category.java
  src/main/java/com/submarine29/market/domain/Order.java
  src/main/java/com/submarine29/market/domain/Product.java
  src/main/java/com/submarine29/market/domain/User.java
  src/main/java/com/submarine29/market/repo/ProductRepo.java
  src/main/resources/sql/data.sql
  src/main/resources/templates/components/upsert_product.ftlh
Labels: enhancement

#69 Работа с кол-вом товара в позиции
  src/main/java/com/submarine29/market/controller/BasketController.java
  src/main/java/com/submarine29/market/domain/Order.java
  src/main/java/com/submarine29/market/domain/OrderItem.java
  src/main/java/com/submarine29/market/domain/Product.java
  src/main/java/com/submarine29/market/services/BasketService.java
  src/main/resources/sql/data.sql
  src/main/resources/templates/basket/basket.ftlh
  src/main/resources/templates/products/list.ftlh
  src/main/resources/templates/products/show.ftlh
Labels: bug, enhancement

#77 Market 67
  build.gradle
  src/main/java/com/submarine29/market/controller/ProductController.java
  src/main/java/com/submarine29/market/dto/DataForFindDTO.java
  src/main/java/com/submarine29/market/repo/ProductRepo.java
  src/main/resources/application.properties
  src/main/resources/templates/basket/basket.ftlh
  src/main/resources/templates/components/pager.ftl
  src/main/resources/templates/components/upsert_product.ftlh
  src/main/resources/templates/products/list.ftlh
Labels: enhancement

#104 Hotfix
  src/main/java/com/submarine29/market/controller/PayPalController.java
  src/main/java/com/submarine29/market/domain/Order.java
  src/main/java/com/submarine29/market/domain/Status.java
  src/main/java/com/submarine29/market/repo/OrderRepo.java
  src/main/java/com/submarine29/market/services/PayPalService.java
  src/main/resources/application.properties
  src/main/resources/sql/data.sql
  src/main/resources/templates/pay/cancel.ftlh
  src/main/resources/templates/pay/success.ftlh
Labels: bug, ВАЖНО

#105 Market-непонятно какой
  src/main/java/com/submarine29/market/controller/PayPalController.java
  src/main/java/com/submarine29/market/services/BasketService.java
Labels: bug
